"""2a differential test: the tgforge render/parse ports must match the reference
bot byte-for-byte over the shared cases. Hermetic — reads only the committed
goldens (generated by goldens/generate.py from the reference module)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from tgforge.base import ui as base_render
from tgforge.plugins.claude import events
from tgforge.plugins.claude import render as claude_render

GOLDENS_DIR = Path(__file__).resolve().parent / "goldens"
sys.path.insert(0, str(GOLDENS_DIR))
import cases  # noqa: E402

GOLDENS = json.loads((GOLDENS_DIR / "render_goldens.json").read_text())


def _resolve(name):
    for mod in (base_render, claude_render, events):
        if hasattr(mod, name):
            return getattr(mod, name)
    raise KeyError(name)


def _norm(v):
    # JSON round-trip so tuples compare equal to the list-shaped goldens.
    return json.loads(json.dumps(v, ensure_ascii=False))


@pytest.mark.parametrize("g", GOLDENS, ids=lambda g: f"{g['group']}:{g['name']}")
def test_port_matches_reference(g):
    fn = _resolve(g["name"])
    assert _norm(fn(*g["args"])) == g["expected"]


def test_goldens_cover_every_case():
    assert len(GOLDENS) == len(cases.ALL_CASES)
